# Generated by Django 5.2.13 on 2026-04-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
