# Generated by Django 5.2.11 on 2026-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_exercisesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
