# Generated by Django 5.2.13 on 2026-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_first_name_studentprofile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='parent_occupation',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
