# Generated by Django 5.2.13 on 2026-04-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'db_table': 'skills',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='users.skill'),
        ),
    ]
