# Generated by Django 5.2.13 on 2026-04-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_skill_exercise_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_importance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
