# Generated by Django 5.2.13 on 2026-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
