# Generated by Django 5.2.11 on 2026-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_active_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'levels',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='classes', to='users.level'),
        ),
        migrations.AddField(
            model_name='skill',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='skills', to='users.level'),
        ),
    ]
