# Generated by Django 5.2.13 on 2026-05-16 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_class_teacher_class_teachers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ClassTeacher',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='users.class', db_column='class_id')),
                        ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teachers', to='users.level', db_column='level_id')),
                        ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teachers', to='users.teacherprofile', db_column='teacher_id')),
                    ],
                    options={
                        'db_table': 'classes_teachers',
                        'unique_together': {('class_obj', 'teacher', 'level')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE classes_teachers (
                        id SERIAL PRIMARY KEY,
                        class_id INTEGER NOT NULL REFERENCES classes(id) DEFERRABLE INITIALLY DEFERRED,
                        teacher_id INTEGER NOT NULL REFERENCES teachers(id) DEFERRABLE INITIALLY DEFERRED,
                        level_id INTEGER REFERENCES levels(id) DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE UNIQUE INDEX classes_teachers_class_id_teacher_id_level_id_uniq
                        ON classes_teachers (class_id, teacher_id, level_id);
                    """,
                    reverse_sql="DROP TABLE classes_teachers;",
                ),
            ],
        ),
    ]
