# Generated by Django 5.2.13 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_classteacher_alter_class_teachers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='enrollment',
                    name='class_obj',
                ),
                migrations.AddField(
                    model_name='enrollment',
                    name='class_teacher',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='enrollment_requests',
                        to='users.classteacher',
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name='enrollment',
                    unique_together={('student', 'class_teacher')},
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE enrollment ADD COLUMN class_teacher_id INTEGER;
                    ALTER TABLE enrollment DROP CONSTRAINT IF EXISTS enrollment_student_id_class_id_key;
                    ALTER TABLE enrollment DROP COLUMN class_id;
                    ALTER TABLE enrollment ADD CONSTRAINT enrollment_class_teacher_id_fk
                        FOREIGN KEY (class_teacher_id) REFERENCES classes_teachers(id) DEFERRABLE INITIALLY DEFERRED;
                    ALTER TABLE enrollment ADD CONSTRAINT enrollment_student_class_teacher_unique
                        UNIQUE (student_id, class_teacher_id);
                    """,
                    reverse_sql="""
                    ALTER TABLE enrollment DROP CONSTRAINT IF EXISTS enrollment_student_class_teacher_unique;
                    ALTER TABLE enrollment DROP CONSTRAINT IF EXISTS enrollment_class_teacher_id_fk;
                    ALTER TABLE enrollment ADD COLUMN class_id INTEGER;
                    ALTER TABLE enrollment ADD CONSTRAINT enrollment_student_id_class_id_key
                        UNIQUE (student_id, class_id);
                    ALTER TABLE enrollment DROP COLUMN class_teacher_id;
                    """,
                ),
            ],
        ),
    ]
