# Generated by Django 5.2.13 on 2026-05-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_enrollment_class_teacher'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='class',
                    name='teachers',
                    field=models.ManyToManyField(blank=True, related_name='classes_taught', through='users.ClassTeacher', to='users.teacherprofile'),
                ),
            ],
            database_operations=[],
        ),
    ]
