# Generated by Django 5.2.11 on 2026-05-17 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(blank=True, db_column='level_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='users.level'),
        ),
    ]
