# Generated by Django 5.2.11 on 2026-05-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_exercise_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='students',
            field=models.ManyToManyField(blank=True, db_table='student_exercises', related_name='assigned_exercises', to='users.studentprofile'),
        ),
    ]
