# Generated by Django 5.2.11 on 2026-05-21 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_exercise_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_exercises', to='users.teacherprofile'),
        ),
    ]
